### ISSUE TITLE
Wiki Home's "Setting it up in Production, Sandbox, or Dev Orgs" leads to a broken link

### ISSUE THREAD

**Issue by MatthewBlanski** [SFDO-Community-Sprints/Summit-Events-App#345]
On the wiki under Home -> Getting Started, the link for "Setting it up in Production, Sandbox, or Dev Orgs" leads to `https://github.com/SFDO-Community-Sprints/Summit-Events-App/blob/master/docs/set-up.md`.

This file no longer exists, resulting in a broken link.

**Comment by rdblake21** [comment]
The link path didn't exist in the Doc folder and those instructions were moved to the Wiki.

Great find!  All updated.
