### ISSUE TITLE
Wiki Home's "Recorded Demo" leads to the app channel instead of the recorded demo.

### ISSUE THREAD

**Issue by MatthewBlanski** [SFDO-Community-Sprints/Summit-Events-App#346]
On the wiki under Home -> Project information, the link for "Recorded Demo" leads to `https://www.youtube.com/channel/UCfc-Xkm-RrNxsK6Bs3KO6Rw`, which is the app channel. The link appears as though it should link to a specific demo video or that it should be renamed to something like "Watch recorded demos on Youtube."

**Comment by rdblake21** [comment]
Changed to YouTube Channel and made a note that more recorded demos are coming.  We haven't done a formal recorded demo in some time based on the intensive development as well as pause in development during security review.  More will be coming!
