### ISSUE TITLE
Multi-day events has timezone formatted oddly in breadcrumb

### ISSUE THREAD

**Issue by hlhcg** [SFDO-Community-Sprints/Summit-Events-App#366]
Multi-day events has timezone formatted oddly in breadcrumb

<img width="778" alt="Screen Shot 2021-10-20 at 3 54 24 PM" src="https://user-images.githubusercontent.com/91471643/138170615-d5688f7f-0f61-4c14-bc97-f27572f320e8.png">

**Comment by rdblake21** [comment]
Coming back to this as I believe this was captured during the October Sprint.  show an example of a time when the year transfers (new years)
![image](https://user-images.githubusercontent.com/60475518/167537117-5a9687bf-af29-412d-92b2-7da3f0cade21.png)

There is some inconsistency on where the year is placed compared to the time and other date formats.

Per the examples, the year in the second portion should come before the time and after the day date.

**Comment by rdblake21** [comment]
Handled on SummitEventsShared.cls, line 469-500

**Comment by rdblake21** [comment]
@tcdahlberg Please review and assess effort prior to packaging.

Ideally it would be:
Friday, December 30, 2022, 8:00 AM - Monday January, 02, 2023 3:30 PM CDT
Wednesday, October 20, 6:00 AM - Friday, October 22, 2022 9:00 AM CDT

So the Time and year need to be flipped on the second date to be consistent with the first.

**Comment by tcdahlberg** [comment]
![image](https://user-images.githubusercontent.com/16785863/214447231-12dc3aad-5b2d-4cd6-8b49-0725202705eb.png)
@rdblake21, I assume the commas after the year were intentional. Your comment above didn't have a comma after the year before the time. I like the way it is in your code change and approve.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
