### ISSUE TITLE
Instance Short Description on Calednar

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#372]
When reviewing the calendar in Summit Events, the Instance Short Description isn't appear on the hover over. It was my understanding that the Instance Short Description is utilized for the calendar so there is some detail in addition to the Instance Title.

**Comment by rdblake21** [comment]
@tcdahlberg Please review this and let me know if this would be easy to add the Instance Short description AFTER the longDesc on the calendar hover over.

So logic like the following:

`IF(longDesc != null, show longDesc && IF(instanceDesc != null, ": " && instanceDesc, ""), "")`

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
