### ISSUE TITLE
Enhancement Request - If no Summit Events Appointment Types are active, remove Appointment Options Page

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#374]
Users in UST Events noticed that if Appointment Type records are on an Event, and even if no Appointment Type records are Active, the Appointment Options page will display during the registration path.  Can this page be removed if no Appointment Type records are active.
![Appointment Options Page](https://user-images.githubusercontent.com/57462572/152049807-6fa9cd58-4386-4649-8017-43568a2c8bc0.gif)

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
