### ISSUE TITLE
[BUG] Phone input not displaying on Add'l Question Reg Page

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#378]
**Describe the bug**
When utilizing the Additional Question, when a "Phone" Question field Type is selected, the input box does not display on the Additional Questions Page.

**To Reproduce**
1. Create an additional question with "Phone" Question Field Type
2. Map to a Phone field, like Registrant_Other_Phone__c
3. Go through the registration process.

**Expected behavior**
Expectation is ability to enter a phone number and have it mapped to the designated registration field.

**Screenshots**
![image](https://user-images.githubusercontent.com/60475518/159073489-12f5d319-154a-492a-9001-00d10ef3b3b3.png)
![image](https://user-images.githubusercontent.com/60475518/159073556-c9649fe5-8569-43da-8930-3d0ba200db55.png)

**Desktop (please complete the following information):**
 - Browser = on Chrome

**Comment by tcdahlberg** [comment]
Included in beta release 0.27.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.27.0.1
