### ISSUE TITLE
[BUG] Lookup Field Type not functioning in Scratch Org

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#380]
**Describe the bug**
When testing the Lookup of Additional Questions in a Scratch org (not a managed package), regardless of the object or Map To Field, the same error of "Question setup issue(s): Map To Field: Field api_name may not exist".  I'm unable to actually have the lookup value appear and I noticed in the code that there is reference to trying to find a namespace of "summit" if appropriate, but if not, to leave it blank.

Part of me is wondering if there is a namespace reference in the Lookup Field Type where it wants to find a namespace, but isn't so doesn't recognize a custom field as valid as it also didn't recognize a field it already has access to writing to. I got the following error when trying to map to Additional Answer 5 on the Event Registration record - "Question setup issue(s): Map To Field: Field add_info_answer_5__c may not exist"

**To Reproduce**
1. Create appropriate permissions set giving access to a custom field on the registration record and supporting object.  Permissions set may give READ access to Accounts with permissions to read the Name and BillingAddress fields.
2. Ensure the Sharing Rule is active for the guest user to see such account records.
3. Create an Summit Event Question record with the "Mapped To" field set as the custom field on the Event Registration record.  This should be validated that the guest user has Edit access to that field
4. Complete the Record Lookup Section on the Question record to lookup to "Account" and Lookup Fields are Name, BillingAddress.
5. Include the Secondary Lookup Fields to be "Registrant_High_School__c" and then hit Save.
6. Create a new Registration and on the Additional Question page, see the error of "Question setup issue(s): Map To Field: Field school_account__c may not exist."

**Expected behavior**
The expected behavior is that a lookup input box appears to see Account records the Guest User has access to.

**Screenshots**
![image](https://user-images.githubusercontent.com/60475518/159203708-d97a2e8e-e985-443e-a45f-06cb839c96b5.png)
![image](https://user-images.githubusercontent.com/60475518/159203730-89d6d837-8b07-49dd-8e84-aa0d0f3bfc7c.png)

**Desktop (please complete the following information):**
  - Browser: Chrome
 
**Additional context**
I also noticed in the code that there is trimming and automatic lowercasing happening. I did attempt to change the API name to all lower case as I originally had it as "School_Account__c".  The error still made it lower case, but it seems that in apex all API names are case insensitive. There may be some confusion when the API name has cased letters, but the error doesn't show it as it's being changed.  Something to consider removing if it isn't going to create further issues so the individual knows that their field matches what they see in salesforce.

**Comment by tcdahlberg** [comment]
Included in beta release 0.27.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.27.0.1
