### ISSUE TITLE
Sticks on Step 4.  Add to page layouts when adding new custom field

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#383]
**Describe the bug**
Sticks on Step 4.  Add to page layouts when adding new custom field.  It does save the field but does not leave the step 4 screen giving the impression is not saving field.  Need to hit Cancel or navigate away to leave screen.

**To Reproduce**
1. Go to the Object Manager and open the Summit Events Registration object.  
2. Click on Fields & Relationships
3. Click the New button 
4. Choose data type Picklist
5. Click Next
6. Give the field a name and picklist values
7. Click Next
8. Select/Deselect field visibility as desired
9. Click Next
10. Click Save

**Expected behavior**
When click Save in step 10, should Save the field and leave the Step 4 screen.

**Screenshots**
Stuck on this screen
![image](https://user-images.githubusercontent.com/4521914/159559302-863e9c9f-ec27-4b49-91fb-d2ec50b961ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Version 99.0.4844.74 (Official Build) (64-bit)

**Comment by rdblake21** [comment]
@dwhitig I'm wondering if this is more of a scratch org issue as I don't know why Summit Events would be causing the issue. @tcdahlberg any thoughts?

**Comment by dwhitig** [comment]
I'm sure it could be!  Did you try it and did not have the issue? @rdblake21

**Comment by walt0019** [comment]
Hi @dwhitig, @tcdahlberg and @rdblake21, just checking on open issues and tested it and didn't have an issue myself with my scratch org (https://fun-page-7695-dev-ed.cs77.my.salesforce.com/).

**Comment by dwhitig** [comment]
@walt0019 @tcdahlberg  @rdblake21  sounds like it's a non-issue then.  I'm going to close this issue.
