### ISSUE TITLE
Remove Dependent Question section from Page Layout[BUG]

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#391]
**Describe the bug**
Remove Dependent question section from Page Layout before newest release as feature is not built out.

1. Go to create a new Custom Questions
2.  Scroll down to the section labeled Dependent Question section

![image](https://user-images.githubusercontent.com/4521914/166983440-4924e341-33da-48ac-9c50-5796bfa91057.png)

**Comment by rdblake21** [comment]
@dwhitig THis is being removed from the page layout and has help text and descripting with the following note: `NOTE: Functionality doesn't currently exist and is on the roadmap.`
