### ISSUE TITLE
Enhancement: Ask Mobile and Ask Require Mobile options within Ask Phone field

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#395]
**Is your feature request related to a problem? Please describe.**
Feedback from the May 2022 Sprint, expected a Ask Mobile and Ask Require Mobile options only.  This request is probably focused from a higher ed, younger demographic perspective, but good call out that most people only operate from a Mobile phone perspective and we should simplify the form data gathering.

**Describe the solution you'd like**
Add additional options, Ask Mobile and Ask Require Mobile, and drive experience on the SEA Registration Page.

**Describe alternatives you've considered**
The form functions today with the Home and Mobile options, but could require, limit and simplify options if there were Mobile only options.

**Are you willing and interested in being engaged during the development and testing process?**
Yes and add Robert Wynter.

**Comment by tcdahlberg** [comment]
Included in beta release 0.29.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.29.0.1
