### ISSUE TITLE
[BUG] If optional question set to None, labels should not appear on registration page.

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#401]
**Describe the bug**
If optional question set to None, labels should not appear on registration page.

**To Reproduce**
1. Go to the event setup and make sure the Add Info Question Type 1
 and put a label in the Add Info Question Text 1 field and save.
2. View the registration page, you will see the label but no prompt box.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4521914/168319129-90f45d38-fdc8-411d-873e-9d24c0715990.png)

![image](https://user-images.githubusercontent.com/4521914/168319364-c2a980a8-ee5e-4f6d-9c37-1a82eb507987.png)

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
