### ISSUE TITLE
Additional Questions:  Text area and Text box fields look the same on reg page

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#403]
**Describe the bug**
What is the difference between Text box and text area additional question types?

**To Reproduce**
1. Go to the additional configuration & Options area.  
2. Set Additional Question 1 to a Text area field and call it's text Text area.
3. Set Additional Question 2 to a Text box field and call it's text Text box.
4. See screenshot

**Expected behavior**
I would expect one field to be a box shape with multiple lines and the other to be a single line box.  Both appear the same on the registration form.   Should one show differently?

**Screenshots**
![image](https://user-images.githubusercontent.com/4521914/168668378-c9bcd4b6-3f85-482f-a3a3-5ec51456b5d8.png)

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
