### ISSUE TITLE
[BUG] - Appointments - Appointment Type - Chosen State

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#405]
**Describe the bug**
When setting up an event and utilizing Appointment/Options, on the Appointment Type, the "Chosen State" field does not do what is expected.  It seems to have no impact to appointments.

**To Reproduce**
1. Create a basic event
2. Create an Appointment Type record with "Chosen State" and select any value (none of them work).
3.  Register for the event
4. Submit the registration. Prior to submitting the registration, you'll see that your appointment type is not impacted by the Chosen State field.

**Expected behavior**
The expectations is that the Chosen State will have a preselected option based on the value selected.

Added - It's already on the right side under "Selected Options"
Added and Required - It's already on the right side under "Selected Options" and shows as required so you cannot deselect it. If you can deselect it, it's still required so much be selected.
Added but not shown - It's added behind the scenes so it doesn't show on the Available Options or Selected options, but upon registration, it creates a related appointment record to the appropriate registration record.

**Additional context**
This functionality may have been stripped out when refactoring from UST Events.  This is going to be needed functionality for schools in the nearer future.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
