### ISSUE TITLE
[BUG] - Appointment Type - Required Appointment (and Input)

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#406]
**Describe the bug**
When creating an Appointment Type and selecting "Required Appointment" (Checkbox = True), without a Registration Input value, the Appointment/Option doesn't allow you to select the requirement option. This stops you from moving forward.

When you update the appointment type to have a registrant input, you can input a value on the required option and then select it appropriately.

If that registration input is not required on a required appointment type/option, you are still required to input something to add it to the Selected Option list.

Overall there are issues with the Required Appointment functionality.

**To Reproduce**
1. Create a basic Event
2. Create an Appointment Type and make "Requirement Appointment" field TRUE.
3. Create a registration and try to select the required option.

1. Create a basic Events
2. Create an Appointment Type and make "Requirement Appointment" field TRUE.
3. Update the "Registrant input"  to "Text Box"
4. 3. Create a registration and try to select the required option WITHOUT inputting text (since inputting text is note required)
5. Input text on the required appointment/option. This should process, but misses the expect behavior.

**Expected behavior**
If there is a requirement appointment/option, you can select it without any registrant input.

If there is registrant input, it should follow the rules associated to the "registrant input" field, so if the value is required, an error message appears saying, please input/select a value.  If it is not required, you can select the required appointment without inputting anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/60475518/169749392-f887049f-caab-4794-a3a3-342fd99dc35d.png)
![image](https://user-images.githubusercontent.com/60475518/169749478-dc600567-a5e0-43cb-babc-ebbf13c8fa89.png)

![image](https://user-images.githubusercontent.com/60475518/169749545-7a8b4c40-5fb4-4fcf-80de-ce6ebe8d6340.png)
![image](https://user-images.githubusercontent.com/60475518/169749565-b896d86b-61b4-4be7-bef7-fe19ac705190.png)
![image](https://user-images.githubusercontent.com/60475518/169749613-536bcee2-73a0-44d4-9572-29bfd1749539.png)

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
