### ISSUE TITLE
[BUG] Can't set default Summit Event template

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community-Sprints/Summit-Events-App#408]
I've set a custom picklist value as the default on the "Template" field on "Summit Events" object, but when I create a new record they still have "GeneralSLDS" as the default value (see screenshots).

![image001](https://user-images.githubusercontent.com/50189636/170084592-342c1515-5f9e-4b03-bb8a-98a8295304d5.png)
![image002](https://user-images.githubusercontent.com/50189636/170084606-601f586d-6303-435d-aba0-73626768571b.png)

I believe this is because the 'Default Value' is populated with the value "GeneralSLDS" in the package, which is overwriting the 'Default' setting on the picklist value. This field is managed so I can't change it. Can this be updated?

![image003](https://user-images.githubusercontent.com/50189636/170084626-6dfd5c25-cb38-49bb-a747-67e8df31db8b.png)

Disabling the "GeneralSLDS" template fixes this problem, but I don't believe that's a good answer.

**Comment by Scarrien** [comment]
@tcdahlberg This is the issue we discussed yesterday, if you want to review it and add any comments that would be great.

**Comment by rdblake21** [comment]
Testing to see if we can remove the default value and set the single picklist value as the default.  That would allow any user to change the default value.  With the field being required, it'll always capture something before the Event is saved.  We should need to have a default value in general options if we can set it on Values list.

**Comment by rdblake21** [comment]
Test was successful.  Going to add to a PR.  Will need to test what happens on the upgrade versus an install to a net new org.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
