### ISSUE TITLE
[BUG] - Global Picklist Values on Question Object

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#413]
**Describe the bug**
When creating a custom question is created on the question object and the field type is picklist, there is an error when the mapped picklist value is set to a Global Picklist Value Set.  It seems to be a permission or functional issue difference with Global Picklist values in the "SummitEventsRegisterGuestsController.cls" that are not in the SummitEventsAdditionalQuestionsCtlr.cls. Utilizing a Global Picklist value  on the registration record field seems to be the issue when on the Additional Question Page, but works when on the Register Guest page. 

**To Reproduce**
1. Create a new picklist field on the Registration record with the values associating to a Global Picklist Value set.
2. Give appropriate access to permissions set associated to the Registrant User
3. Create a Custom Question record with an Registrant Type of "Registrant"
4. Complete the rest of the fields for the Registrant to be able to answer the custom question on the Additional Question page.
5. Be sure the Event record is display Guest to test that this works for Guests and turn off when testing the Registrant.
6. Register and see error.

**Expected behavior**
Expectation is that the question appears on the Additional Questions Page similarly to the Guest Registration page.

**Screenshots**
Guest Question Experience with Global Value Set
![image](https://user-images.githubusercontent.com/60475518/172226140-7b83d63f-839f-485c-9c86-2d85f26441a0.png)
![image](https://user-images.githubusercontent.com/60475518/172226060-a6eec56f-edc3-42f1-8de5-8eb49fc72d67.png)

Registrant Additional Question Experience with Global Value Set
![image](https://user-images.githubusercontent.com/60475518/172226459-1ec3f60c-e3ea-4318-82c0-f051fdd40612.png)
![image](https://user-images.githubusercontent.com/60475518/172226383-b559b9b5-c8e2-48e1-994e-8f283ec2841a.png)

Note that the permission set is not the issue as you can see the values for the other Registrant Type.

**Additional context**
This is a known issue and the current work-around is to not use Global Picklist Values. This will be fixed in the next release.

**Comment by rdblake21** [comment]
This is also seeming to happen while packaged with standard picklists.  Thad is looking into this and may have a quick fix already.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
