### ISSUE TITLE
[BUG] - Custom Questions Object - selecting "Registrant and Guest" is skipping pages entirely

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#414]
**Describe the bug**
When creating a custom question on the question object and the registrant type is "Registrant and Guest", the expected additional question page is getting skipped. When reviewing "SummitEventsRegisterGuestsController.cls" and "SummitEventsAdditionalQuestionsCtlr.cls" they seem to have the logic to work appropriately, but something seems to not acknowledge the additional question aspect appropriately. 

**To Reproduce**
1. Create a Custom Question record with an Registrant Type of "Registrant and Guest"
2. Complete the rest of the fields for the Registrant to be able to answer the custom question on the Additional Question page.
3. Be sure the Event record is display Guest to test that this works for Guests.
4. Notice that both pages are skipped

**Expected behavior**
Expectation is that the question appears on the Additional Questions Page as well as the Guest Registration page.

**Screenshots**
![image](https://user-images.githubusercontent.com/60475518/172228217-fa773ac6-42f5-41a1-a719-15b33e4da268.png)
![image](https://user-images.githubusercontent.com/60475518/172228385-853478bd-2f9b-4fab-9b1a-afb938741ac4.png)

There is no Additional Question page that appears.

**Additional context**
This is a known issue and the current work-out is to create Registrant and Guest question seperately.  You can do this by hitting "clone" while on your originally created record and then change the Registrant Type on the cloned record.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
