### ISSUE TITLE
[BUG] - Instance Capacity Control Calculation error on "Individual Registrant"

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#415]
**Describe the bug**
When setting up the instance and the Capacity Control is set to "Individual Registrant", the instances "Closes" when registrations are in a started Status.  If you change the Capacity Control to "Registrant, plus Guest", the available works as expected.

The "Current Available Capacity" is controlled by a couple of rollup summary fields. The formula is as such:

```IF(ISPICKVAL( summit__Capacity_Control__c, "Registrants plus Guests"), summit__Capacity__c - summit__Count_of_Attendees__c, summit__Capacity__c - summit__Primary_Attendees__c)```

While that seems accurate, when reviewing  "summit__Count_of_Attendees__c" and "summit__Primary_Attendees__c", Count of Attendees is eliminating registrations in a "Started" status, which is appropriate as we don't want to include those in the event.  When looking at Primary Attendees, the rollup is calculated different, but include registrations in a "Started" status, meaning based on the Current Available Capacity, when Individual Registrant is selected, Started registrations will count towards the Capacity limit.

**To Reproduce**
1. Create an Events
2. Create an Instance and set the "Capacity Control" to "individual registrant"
3. Complete the first page of registration (if only the registration page, change the registration record to "Started")

**Expected behavior**
Started status on Registrations should not count as "Primary Attendees" as they are not registered.

**Screenshots**
![image](https://user-images.githubusercontent.com/60475518/174332545-53fd449a-e14d-42bd-8c36-0ce721196bfe.png)
![image](https://user-images.githubusercontent.com/60475518/174332665-41c0bb2f-e397-4c46-a2f1-799df24a436e.png)

**Additional context**
Based on the Roll Up Summary fields that are controlling this, we need to update the Primary Attendees Roll Up Summary to be "

```Filter Criteria | Status NOT EQUAL TO Cancelled, Rescheduled, Started```

**Workaround**
Current workaround is to keep the "Capacity Control" to Registration plus Guest

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
