### ISSUE TITLE
[DOCUMENTATION] Update Setup Instructions

### ISSUE THREAD

**Issue by Kathy-Lueckeman** [SFDO-Community-Sprints/Summit-Events-App#416]
There are three updates that could be made.

1. In the setup instructions, the document says to use the Action column but in my sandbox, I had an Activate button at the top of the page.

Current: Upon save, you will see the Site under the Sites section. Under the Action column, click the "Activate" link (next to the site you just created).

Proposed: Upon save, you will see the Site under the Sites section. Click the "Activate" at the top of the page.

2. In the Apply Summit Events Registrant permission set to the Guests User of Your Site documentation it says View Users button but in the system it’s Assigned Users button:

Current: On the Summit Events Profile page, click on the "View Users" button.

Proposed: On the Summit Events Profile page, click the Assigned Users button

3. Under the Select the users to share with, the documentation says the only option is Summit Events Guest User but only option I had was Event Site Guest User.

**Comment by dwhitig** [comment]
Thanks @Kathy-Lueckeman for taking the time to outline these items!  I'll talk to @tcdahlberg and we'll work to get the documentation updated.

**Comment by dwhitig** [comment]
@Kathy-Lueckeman I have made updates to the documentation based on your suggestions.  Would you mind reviewing them and let me know if the changes make sense?

https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/Getting-Started/Installing/

**Comment by rdblake21** [comment]
Updates have been made based on proposed updates
