### ISSUE TITLE
[BUG] "Map to Field" on Summit Events Question needs to be required

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community-Sprints/Summit-Events-App#417]
"Map to Field" on Summit Events Question needs to be required. If this field doesn't have a value, then the answer a person submits won't be stored anywhere which makes the whole question record irrelevant.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
