### ISSUE TITLE
[BUG] Validation rules need to be made on Summit Event Question

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community-Sprints/Summit-Events-App#418]
The Admin for a client was creating a lookup field type and missed some of the fields required to do this, and these missing field values on the question setup gave them error messages when trying to use the form.  We need some validation rules that don't allow a person to enter a custom question unless they complete all the required fields needed for that field type. 

Also if a picklist field type is selected then the user needs to either add picklist values or select a picklist value set. A validation rule needs to be made to ensure the correct fields are completed for Picklist field type.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
