### ISSUE TITLE
[BUG] Rename "Additional Question" fields

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community-Sprints/Summit-Events-App#419]
The title and description fields that appear on the Custom Question pages are called "Additional" questions title and description - this is confusing because they aren't used on the page where Additional Questions display (these field labels need to be changed to "Custom Question" title and description).

**Comment by rdblake21** [comment]
Update the following with reasoning:
- `FlexiPage: Summit_Events_Record_Page` - Changed the Label on the Page Details Tab from "Additional Questions Page" to "Custom Questions Page". Update made based on confusion between the "Additional Questions" that will appear on the main registration page, which is managed on another tab (Add'l Configuration Options) and the page where the Summit Event Questions related records will appear, which is on a Custom Questions page.
- `Summit_Events__c.Event_Additional_Question_Title__c` - Updated label to change Additional to Custom and updated Help and Description text to reflect that it is the page that'll capture related list custom question records more appropriately
- `Summit_Events__c.Event_Additional_Questions_Description__c` - Updated label to change Additional to Custom and updated Help and Description text to reflect the page that'll capture related list custom question records more appropriately

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
