### ISSUE TITLE
[BUG] Misspelled Word on Summit Events Email Screen

### ISSUE THREAD

**Issue by Kathy-Lueckeman** [SFDO-Community-Sprints/Summit-Events-App#422]
**Describe the bug**
The help text for the Letterhead ID field uses the word "idea" instead of "ID." It says, "The idea of the selected letterhead from the org." It should read, "The ID of the selected letterhead from the org."

**To Reproduce**
1. Go to the Summit Events App
2. Click on the Summit Events Email tab.
3. Click new
4. Hover over the Letterhead field at the bottom of the screen to view the help text.

**Expected behavior**
It should read, "The ID of the selected letterhead from the org."

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Macbook Pro
 - Chrome
 - Version 103.0.5060.53

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
