### ISSUE TITLE
[BUG] "Keep Registration Open During Event" checkbox does not work for multi-day Event Instances

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community-Sprints/Summit-Events-App#425]
**Describe the bug**
When you have a multi-day Summit Event Instance, the "Keep Registration Open During Event" checkbox on the Summit Event record does not keep the event open. Instead, the event closes after the first day has passed.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
