### ISSUE TITLE
[BUG] Summit Event Registrations created from "New" button in Salesforce don't have needed validation

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community-Sprints/Summit-Events-App#431]
If a Salesforce user adds or edits a new Summit Event Registration record from within Salesforce, there isn't validation on the page layout to ensure the record is created correctly. This results in null pointer exceptions in triggers in our package and missing data relationships.

__Specific problems__
* Instance field needs to go before Event on layout
* Event must be required on page layout

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
