### ISSUE TITLE
[BUG] - Email Visualforce Page

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#435]
**Describe the bug**
When trying to create an email, there is an error when the visualforce page tries to load. This makes it challenging in being able to setup the email appropriately as I can no longer select the Email or Template.

**To Reproduce**
1. Create an Event
2. Create a related Summit Event Email record. No details are needed to see the error.

**Expected behavior**
The expectation is that the VF page loads with a drop down of org-wide email addresses as well as classic email templates to choose from.

**Screenshots**
![image](https://user-images.githubusercontent.com/60475518/192385042-38abedb4-cff6-4cb9-9ee6-ef251fd61c8d.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 0.27.0.1

**Additional context**
This was a new feature in the latest release and this error is occurring in a production org with the latest release installed. When creating a scratch org, it functions as expected.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
