### ISSUE TITLE
[BUG] Managed package custom report types don't include Contact/Lead ID fields

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community-Sprints/Summit-Events-App#436]
Our custom report types (such as Summit Events Registrants) contain the Contact and Lead lookup fields which displays the name on the report, but they don't include the Contact ID or Lead ID fields in any way. Since managed packages can't be edited by the user, to add fields they need to make an identical custom report type just to add these basic fields.

These ID values are critical for using these reports for any type of integration (such as bulk texts from Mogli) or Dataloader. It would be easy to create and add them to the managed reports.

**Comment by rdblake21** [comment]
#430 also captures this same sentiment
