### ISSUE TITLE
[FEATURE] Appointments - Summary page should respect sort order of appointment

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#437]
After registrant choses appointments and goes to next page, a summary of what they have chosen is displayed however, it is not displaying in the order specified in setup.  Would be nice if the summary screen obeyed the sort order like the screen where they choose the options.

I put numbers in the Sort order field when I setup the Appointments.  The screen where they select the appointments, is displaying the items according to how I have them ordered.

![image](https://user-images.githubusercontent.com/4521914/195699208-3f4fe6a4-cb67-4e77-9a0e-caf67c9ab280.png)

However on the summary screen, that shows the selections they made, it does not retain that sorting order.
![image](https://user-images.githubusercontent.com/4521914/195698810-07fff217-8f2a-49a2-86e8-a6e09b4255c2.png)

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
