### ISSUE TITLE
[BUG] Appointment Type - Remove Appointment Type field from Pagelayout

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#441]
**Describe the bug**
The appointment type field is not meant to be displayed to event manager and can be confusing.  It should be removed from the page layout.
![BUG-Appointment Category Field](https://user-images.githubusercontent.com/4521914/202786838-a9ade1b6-3738-4551-b42f-c2b60a156753.PNG)

**Comment by walt0019** [comment]
I updated this within a Scratch Org.  I will follow up with @tcdahlberg on next steps.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
