### ISSUE TITLE
[BUG] - Text Area needs to be Text Area (long)

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#446]
**Describe the bug**
When creating a custom question and utilizing a "picklist" field type, there is a limit of 255 characters because it is a Text Area field.  This limit the number of values you can input, creating challenges when you're wanting to input a list of majors or an extended list overall.

**To Reproduce**
1. Create a Question record and follow appropraite steps for a Custom Question with a Registrant Type of Registrant (though it won't matter)
2. Select "Question Field Type" as Picklist
3. Enter more than 255 characters in the "Picklist Values" field.
4. Try to save the record

**Expected behavior**
Expecting to be able to enter a more extensive list that would be closer 10,000 characters.  Anything beyond that may be looking to better leverage a "Lookup Picklist" now that it's an option.

**Screenshots**
![image](https://user-images.githubusercontent.com/60475518/209910062-0df8d317-834a-428d-91df-0d6f7aa5c4fb.png)

**Additional context**
When trying to create a new branch and make the edit to submit as a pull request, I'm unable to change the field type to "Text Area (Long)" because of the reference in the Apex Class (see image below).  The context of the error is:

*There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Cannot change field type of a custom field referenced in Apex class or trigger: "<a href=/01pDP000006HLou">SummitEventsRegisterGuestsController</a>.*

![image](https://user-images.githubusercontent.com/60475518/209910092-c4cbdff0-8f9c-4cd2-b751-9b499a31cb0a.png)

**Comment by rdblake21** [comment]
@tcdahlberg see the error when I tried to make the fix.  Wondering if we need to either create a new field and update the apex class as that may better support the packaging process and not break hierarchy as it would be deprecating a field.  Just a thought!

**Comment by rdblake21** [comment]
@tcdahlberg testing the aug-23 branch - this functionality isn't working.  The field is there and the validation rule works, but values don't populate when using the Long Text field.  It should work with either of them having values or both having values.  WHile I don't like the fact that we have two fields... we have to think about what that transition looks like for current users..

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
