### ISSUE TITLE
[BUG] - Update Readme link from Wiki to Read the Docs site

### ISSUE THREAD

**Issue by kreynen** [SFDO-Community-Sprints/Summit-Events-App#453]
**Describe the bug**

While there's an "alert" on the top of https://github.com/SFDO-Community/Summit-Events-App/wiki about the most recent version of documentation now being at https://sfdo-community-sprints.github.io/summit-events-app-documentation/, but is there a reason to send users to the wiki? https://install.salesforce.org/products/SummitEventsApp/latest already links to the Read the Docs.

**Comment by kreynen** [comment]
@tcdahlberg thanks for the merge, but I'm really trying to understand the process more than make changes to a project :)

When cleaning up https://github.com/SFDO-Community-Sprints/MembershipSchemaAndBenefits, I'm noticing several things some of the more mature Commons projects have that MembershipSchemaAndBenefits doesn't. Things I'm used to like something that closes the GitHub issues when a related PR is merged.

The CLA service has some issues. After the initial failure, I tried following the link from GitHub and got this error...

<img width="867" alt="Screenshot 2023-02-03 at 12 17 57 PM" src="https://user-images.githubusercontent.com/385234/216689339-2153b6d2-5c1c-4a62-95d3-1dc0f5761c2c.png">

Then I followed the link in the email, authenticated to GitHub and completed the form, but got an error saying `Could not sign the CLA, please contactoss-cla@salesforce.com`. I thought maybe changing my name from my "funny" Kevin + Beard + Drupal to my real name caused the problem so I tried again. Then I get...

<img width="668" alt="Screenshot 2023-02-03 at 12 19 34 PM" src="https://user-images.githubusercontent.com/385234/216690587-ee08ac8b-d06a-43c4-8cc7-e1c975da343a.png">

https://github.com/SFDO-Community/Summit-Events-App/pull/454 still says CLA is missing. I'll follow up with the email address from the CLA error. I opened https://github.com/SFDO-Community-Sprints/Welcome/issues/2 after the San Francisco sprint. I'm going to close this and continue to make some more notes on that issue about the defaults that projects like this are already doing that might make it easier for new projects/contributors if they were included in a template.

**Comment by tcdahlberg** [comment]
@kreynen ,

As far as closing issues I usually just use one the the keywords for closing an issue and the the issue number preceded by the # sign. You can see it in my current pull request. Not sure if that is what you are getting at. The CLA thing was set up by Salesforce.org on an organization level. I'm not ever sure how that works.
