### ISSUE TITLE
[BUG] - Appt Type - Required Custom Pick List Validation and Selection Option 

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#455]
**Describe the bug**
On the Appointment Type Record, there are options for registrant input under Appointment Options. When selecting "Required custom pick list", the registrant experience seems to be lacking the input box.  Without the ability to input the value, the options is not able to be selected.  There seems to be an issue on the visual force page where the box isn't surfacing when this is selected.

**To Reproduce**
1. Create a scratch org
2. Go to the "Test Event" Summit Event record
3. Select "Quiet Time" Appointment Type and update Registrant Input to "Required custom pick list"
4. Select an instance and register, getting to the appointment screen.

**Expected behavior**
The Registrant should be able to see a picklist and required to select an option if they want that option/appointment.

**Screenshots**
![image](https://user-images.githubusercontent.com/60475518/217441886-4c3de2eb-0bf8-40a2-9a21-7e856db28c74.png)
![image](https://user-images.githubusercontent.com/60475518/217441823-911c8b4d-eece-45be-81d1-ea071a02b8bb.png)

**Additional context & potential fix**
Look at Line 110 on the SummitEventsRegisterAppointment.page  There is a missing "a" after the first "||" statement. It doesn't know what to reference.  Noticed that first thing, but I'm guessing there are other implications.

On the SummitEventsRegisterAppointmentCtlr.class, line 173 should read `if (apt.Registrant_Input__c == 'Custom pick list' || apt.Registrant_Input__c == 'Required custom pick list')` It's currently missing the Or statement.

Even with the above updates, there seems to need to be additional validation needed on the PAGE as you can select an option, remove it, deselect and option and still select it when a selection should be required to actually select it.

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
