### ISSUE TITLE
[BUG] - Hardcoded values on the Submit Page

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#464]
**Describe the bug**
The Submit page currently has hardcoded values that should read the labels/headers of their respective pages. Currently it's hardcoded as Appointments, which  may not meet all use cases.

**To Reproduce**
1. Create a normal event with appointment types and Guests
2. Create a new registration and get to the submit page.
3. You'll see the header are hardcoded and don't match the respective page headers.

**Expected behavior**
I had expected they'd match so if the term Appointment wasn't being utilized, it would reflect what was chosen for that page when setting up the event.

**Screenshots**
Line 86 and line 108 on the SummitEventsSubmit.page need to be updated to have fields that are dynamic content. This is the screen shot of me changing the hardcoded label.
![image](https://user-images.githubusercontent.com/60475518/219495508-e54a6271-09eb-485f-888f-97aa3e0bc1e6.png)

**Additional context**

**Comment by tcdahlberg** [comment]
Included in beta release 0.29.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.29.0.1
