### ISSUE TITLE
The Registration Page errors when an Appointment Type has a picklist with only one value.  IE, the Appointment Category only has one Appointment Type value tied to it.

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#467]
**Describe the bug**
The Registration Page errors when an Appointment Type has a picklist with only one value.  IE, the Appointment Category only has one Appointment Type value tied to it.

**To Reproduce**
1. Go to Appointment Types and create an Appointment Type record with an Appointment Category that only has one or zero associated values to the Appointment Category.
2. Now start a registration for the Event Instance.
3. When a user gets to the Appointment Type registration section, the page errors.

**Expected behavior**
An admin user creating the event would expect an error when creating this Appointment Type or some indicator that there is an issue before registrants would see this. 
-

**Comment by tcdahlberg** [comment]
Included in beta release 0.29.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.29.0.1
