### ISSUE TITLE
Receiving Error when registering with the Admin Open Registration link

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#469]
Receiving Error when registering with the Admin Open Registration link

**To Reproduce**
1. Go to Instance and open the Admin Open Registration link
2. Complete the registration and when hitting submit
3. The Event Closed Display Text appears even though the date is open and capacity remains.

**Expected behavior**
The registration is completed within the form and the registration record is status is Registered.  Currently the registration record is created but is in a Started Status.

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
Thad believes there could be an issue with the URL and how appex is understanding 1.  If we change the URL from "https://uofstthomasmn--edastaging.sandbox.my.salesforce-sites.com/summit__summiteventsconfirmation?adminopen=1&instanceID=a0z8A000001vfh4" to "https://uofstthomasmn--edastaging.sandbox.my.salesforce-sites.com/summit__summiteventsconfirmation?adminopen=TRUE&instanceID=a0z8A000001vfh4" it processes the registration to Registered and displays Confirmation page.

**Comment by tcdahlberg** [comment]
Included in beta release 0.29.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.29.0.1
