### ISSUE TITLE
[FEATURE] Add Google Analytics campaign tracking codes to registration

### ISSUE THREAD

**Issue by tcdahlberg** [SFDO-Community-Sprints/Summit-Events-App#473]
**Describe the solution you'd like**

To track the campaign analytic success of a registration google analytic parameters should be recorded on the registration. These should be gathered from the URL, sanitized, and recorded on the registration. Here is a list of those parameters:

- utm_source
- utm_medium
- utm_campaign
- utm_content
- utm_term
- gclid
(Google Click Identifier: Can be uploaded back to the Google Ads platform where they use AI to find similar people)
- utm_id
- utm_source_platform
- utm_creative_format
- utm_marketing_tactic
 
[The definition for each of these parameters can be found here](https://support.google.com/analytics/answer/10917952?hl=en#zippy=%2Cin-this-article).

**Comment by rdblake21** [comment]
Can test leveraging the URL Builder - https://ga-dev-tools.google/ga4/campaign-url-builder/

**Comment by tcdahlberg** [comment]
Included in beta release 0.29.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.29.0.1
