### ISSUE TITLE
Add BCC Transactional Email feature into Summit Events

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#474]
**Describe the solution you'd like**
As the St. Thomas Visits and Events Team move off of UST Events, they are raising issues on functionality not found in Summit Events.  With this issue, they would like the ability to BCC parents and others when sending out reminders/appointments for perspecitive students.  Within UST Events on a Registration record there is a field to add multiple email addresses, comma sepearated on a record and thus also emailed when sending transactional email. 

Thad mentioned that he has access to the code.

**Are you willing and interested in being engaged during the development and testing process?**
Yes

**Comment by tcdahlberg** [comment]
Included in beta release 0.29.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.29.0.1
