### ISSUE TITLE
[Help Text] Help text wording structure 

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#489]
**Describe the bug**
The help text for the Event Name field. should be updated to read a bit clearer.  Change FROM Name of event and displays on registration page  TO Name of the event that displays on the registration page.

![HelpTextConfusing](https://github.com/SFDO-Community/Summit-Events-App/assets/4521914/22aa32b0-032e-4880-85a1-583d1fb05ede)

**Comment by tcdahlberg** [comment]
Included in beta release 0.30.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.30.0.1
