### ISSUE TITLE
[Help Text] Type-o in Help Text for Private Event checkbox

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#490]
The word display is missing the "L".
![HelpText-typeo](https://github.com/SFDO-Community/Summit-Events-App/assets/4521914/81c1b003-f4e5-43d4-bcaa-51d50a3c9ef1)

**Comment by tcdahlberg** [comment]
Included in beta release 0.30.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.30.0.1
