### ISSUE TITLE
[FEATURE] Location Filter for "Location Type Override" 

### ISSUE THREAD

**Issue by mad2492** [SFDO-Community-Sprints/Summit-Events-App#494]
**Is your feature request related to a problem? Please describe.**
We are only able to filter event instances based on the main Event record's location. We are offered a Location Filter but it only works at the Event-level. For example, we cannot filter Online instances of an Event if the Event is initially On-Site.

**Describe the solution you'd like**
Ideally, we would like to be able to filter by location at the instance levels so the JSON returns the subset of instances in a certain location.

**Describe alternatives you've considered**
Creating different events for each location would alleviate the issue but then that defeats the purpose of the "Override" feature in Event instances!

**To help determine if a recipe may be more appropriate, please share other use cases, if possible, this functionality would benefit from.**
This would benefit all users that use the eventFeed JSON and want to make use of the flexibility provided by the Location Override fields.

**Are you willing and interested in being engaged during the development and testing process?**
Absolutely, please loop me in as necessary.

**Comment by tcdahlberg** [comment]
@mad2492 , would adding a filter parameter for location and locationType into the REST API feed accomplish this? I've noticed a few areas where overrides aren't accounted for in the feed so some careful adjustments will need to be made. I played with adding a locationtype additional url parameter with some success. Would that fix your issue in the short term?

**Comment by mad2492** [comment]
@tcdahlberg Hey Thad, locationtype should meet our needs for the time being

**Comment by tcdahlberg** [comment]
Included in beta release 0.30.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.30.0.1
