### ISSUE TITLE
[FEATURE] Additional Questions should be Text Area (Long)

### ISSUE THREAD

**Issue by mad2492** [SFDO-Community-Sprints/Summit-Events-App#495]
**Is your feature request related to a problem? Please describe.**
We cannot use the Additional Questions Picklist to its full potential, due to the size limits of the field. 255 is too restricting.

**Describe the solution you'd like**
Convert the Text Area(255) to a Text Area (Long) so all users of SEA can freely use the Picklist(s)  

**Describe alternatives you've considered**
For our use-case, Open House events - we intended to use the Picklist to list all our Programs so the registrant may select one of interest. We have too many and the picklist was cut short. Our current alternative is to offer only 1 Program "Undecided" and our recruiters will have to go through the RSVP afterwards and update the records to the correct Program of Interest afterwards.

Question object did not fit our use-case because this simple 1 question being isolated on another page felt bad, from a User-Experience perspective.

**To help determine if a recipe may be more appropriate, please share other use cases, if possible, this functionality would benefit from.**
Any picklist can easily max out after just a few options in the current state. Placing arbitrary limits on # of picklist options because of a field-size in the backend can be frustrating to the end-user. For us, at least, the Additional Questions are only usable for small use-cases and we need to be able to add as many options as necessary for a given event. It's a high-priority item on FIU's side. 

**Are you willing and interested in being engaged during the development and testing process?**
Absolutely - let me know when/where.

**Comment by tcdahlberg** [comment]
@mad2492 , I need to investigate if a text area can be changed to a long text area without hurting the ancestry of the manage package.

**Comment by mad2492** [comment]
@tcdahlberg  Fair enough!
Maybe we can add another question then, and that one could be long text?

**Comment by rdblake21** [comment]
@tcdahlberg  testing - need to update page layout to be consistent.  Additional Question 4 is missing the field on the page layout.

otherwise the functionality works as expected in branch aug-23

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
