### ISSUE TITLE
[BUG] Checkbox for "Registrant Receive Texts" appears as required even if the Phone field is optional.

### ISSUE THREAD

**Issue by mad2492** [SFDO-Community-Sprints/Summit-Events-App#497]
**Describe the bug**
Checkbox for "Registrant Receive Texts" appears as required even if the Phone field is optional.

**To Reproduce**
Add Phone to RSVP page, option "Ask Mobile"
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/04453e09-6e8f-4b94-a17f-7bdab7812b7f)

**Expected behavior**
At a minimum, _if_ someone enters a number in the Phone field, _then_ the"Registrant Receive Texts" should appear, and be required. 

Ideally, it would be nice to maybe toggle that checkbox related to Phone Numbers. 

**Screenshots**
![bug1](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/4111a2c3-d485-404a-9ddd-81fda22cc846)

**Comment by tcdahlberg** [comment]
Included in beta release 0.30.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.30.0.1
