### ISSUE TITLE
[FEATURE] Respect New Org Wide Email Permissions

### ISSUE THREAD

**Issue by tcdahlberg** [SFDO-Community-Sprints/Summit-Events-App#498]
With Summer '23 release org wide email address can be permissioned. We need to make the letterhead/email setting tool be more aware of these permissions and open up emails that have been permissioned to SEA. This is difficult because of the various users that SEA runs; From the guest user to the admin user to the logged in community user.

**Comment by rdblake21** [comment]
Duplicate issue submitted
