### ISSUE TITLE
[BUG] External payment page not working in payment page flow.

### ISSUE THREAD

**Issue by tcdahlberg** [SFDO-Community-Sprints/Summit-Events-App#499]
External payment page not working in payment page flow.

**Comment by mad2492** [comment]
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/532165cd-82b1-41e1-8d4f-824bba363e81)
Here is the error at the end of the process (on the confirmation page).

**Comment by tcdahlberg** [comment]
Included in beta release 0.30.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.30.0.1
