### ISSUE TITLE
Guest Registration functionality needs to be more user friendly.   I have suggestions on how to make this screen better.

### ISSUE THREAD

**Issue by koll2427** [SFDO-Community-Sprints/Summit-Events-App#502]
**Describe the solution you'd like**
I have an event/instance configured to allow for guest registrations.   Currently our registrants miss the **_+Register Guest_** button and they click the **Next** button as it is more prominent and BLUE.   See link below for screen shot.

I propose that if someone types anything in the First Name and/or Last name that the **+ Register Guest** button turns blue and the **Next** button turns white and is disabled until the registrant clicks the **+ Register Guest** button.   At that time the **Next** button turns blue again and the **+ Register Guest** button turns white again.   If the user enters another first name and/or last name, the color of those two buttons switch again.

Let me know if you need any additional/clearer details on what I'm suggesting here.   We need this new enhancement completed before we can start using this new guest feature.   Our registrants are getting confused on what to click on with the current configuration.

Thanks for your consideration for this enhancement!

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/78053901/512d9c5e-bbd6-4aee-925f-2d50255601a9)

**Comment by koll2427** [comment]
Thanks you for completing this so quickly!  :-)

**Comment by tcdahlberg** [comment]
Included in beta release 0.30.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.30.0.1
