### ISSUE TITLE
[BUG] Capacity Control doesn't respect hosted registrants

### ISSUE THREAD

**Issue by tcdahlberg** [SFDO-Community-Sprints/Summit-Events-App#504]
On the instance when "Capacity Control" is set to "Individual Registrants" while utilizing the ability for registrants to create their hosted guest registrants the capacity number does not reflect that hosted registrants are not individual registrants.

**Comment by rdblake21** [comment]
Documentation will want to reflect that Allow Other Attendees and Max Other Attendees and Guest Registration (the entire tab) are separate and may impact capacity if used together.  

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/4d5403e2-d760-4c47-bbb5-a7cdc8f4beb6)

**Comment by tcdahlberg** [comment]
Included in beta release 0.30.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.30.0.1
