### ISSUE TITLE
The Preferred Fist Name Formatted field on Summit Events Registration is mislabeled or misunderstood.

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#510]
**Describe the bug**
The Preferred Fist Name Formatted field on Summit Events Registration is mislabeled or misunderstood.  Users are expecting it to just show First Name or Preferred Frist Name, but are not expecting Last Name to be in the field.  Users are also expecting some formatting to happen with proper capitalization.

**Additional context**
I think we should update a Description and Help Text at the least.  I may have to build a custom field in the interim.

**Comment by rdblake21** [comment]
Closing Issue as it was a part of the latest Pull Request #546 and a duplicate of #531
