### ISSUE TITLE
[BUG] Zip Code Triggers an API look-up, which does not always return a City value.

### ISSUE THREAD

**Issue by mad2492** [SFDO-Community-Sprints/Summit-Events-App#511]
**Describe the bug**
When you type a zip code in on the Registration Page, there is an api request to openstreetmap to grab the related city. But this API does not seem to always return a city value. So "Undefined" is populated into the City field on the form. 

**To Reproduce**

Setup a Summit Event that has the Zip Code field on it. Sample here: https://fiucrm--uat.sandbox.my.salesforce-sites.com/fiubusiness/summit__SummitEventsRegister?instanceID=a1Q7i000005WEpe

Type in Zip: 33187 or 33199 or 34479.. 

**Expected behavior**
I expect a blank value to populate in the City on the form if nothing is returned from the lookup JSON. "Undefined" is problematic. As a user, I dont want to see Undefined or maybe I wont even notice and proceed to checkout with this incorrect city value.
Many of the Florida zip-codes I was trying have this issue. 

We need some error-handling when reading back the JSON :) 

Here is an example:
https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&addressdetails=1&postalcode=33187&country=united%20states

**Screenshots**
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/b06039ed-31d0-4586-948b-f094acefa25f)

**Comment by rdblake21** [comment]
Tested and this seems to be working as outlined above in the aug-23 branch

**Comment by walt0019** [comment]
Confirmed that this field worked for me as well.

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
