### ISSUE TITLE
When registering for an Event using Preferred Class Year, the registration form gives them impression it is a picklist field, but it is a text field with validation.

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#512]
**Describe the bug**
When registering for an Event using Preferred Class Year, the registration form gives them impression it is a picklist field, but it is a text field with validation.  Can the "picklist arrows" be removed from the right of the field.

**To Reproduce**
1. Register for an event using Ask Preferred Class Year.
2. Navigate to the question, notice the arrows to the right.
3. See 1 or -1 appear when hitting arrows.

**Expected behavior**
Expect no arrows or anything to indicate a picklist.

**Screenshots**
Attached

**Additional context**
The front end validation on the field is great requiring a class year from 1900 to 2099, but it would be great to remove arrows.  We can provide additional help text in the label or assume the user will figure it out.
<img width="329" alt="Preferred Class field arrows" src="https://github.com/SFDO-Community/Summit-Events-App/assets/57462572/39c23bfd-7b71-4995-a007-80ee2eb92e54">

**Comment by rdblake21** [comment]
@tcdahlberg we should add error text.  Once the error happens, the values are clears and the box turns red, but there is no context.  Add generic error text that says, "Please enter a valid value"

**Comment by walt0019** [comment]
Confirmed that this update/field looks good.  Thanks!

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
