### ISSUE TITLE
[BUG] Add'l Questions Text Box and Text Area are reversed

### ISSUE THREAD

**Issue by mad2492** [SFDO-Community-Sprints/Summit-Events-App#513]
**Describe the bug**
When configuring Additional Questions, the "Text Box" option creates a Text Area on the template and the "Text Area" option creates an Input field on the template. 

**To Reproduce**
Create a New Event, and populate the Additional Questions 1 .
If you select "Text area required" - the field will be an Input box on the rendered form. 
If you select "Text box required " - the field will be a Textarea on the rendered form. 

**Expected behavior**
I expect a Text Area on the template if I select "Text Area" 
I expect an Input field if I select "Text Box"

**Screenshots**
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/759daaf2-3e5c-4d2c-bdf9-f7e465c6e6e6)
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/f239a271-fae5-4c73-bdb9-d810d0600a1f)

**Desktop (please complete the following information):**
Firefox

 

**Additional context**

**Comment by rdblake21** [comment]
Testing in a branch and all looks good.

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
