### ISSUE TITLE
[FEATURE] - Guest Registration Screen restrict user from pushing Next when entered Guest Info is not Registered

### ISSUE THREAD

**Issue by mcke0100** [SFDO-Community-Sprints/Summit-Events-App#514]
This is a similar request to issue 502 which helped by turning the +Register Guest button blue once the user enters guest information. We still have concerns that our registrants miss the +Register Guest button and click the Next button without pressing the +Register Guest button. 

I propose that if someone types anything in the First Name and/or Last name that the Next button turns white and is disabled until the registrant clicks the + Register Guest button. At that time the Next button turns blue again. If the user enters another first name and/or last name, the color of those two buttons switch again.

Let me know if you need any additional/clearer details on what I'm suggesting here. We will use customizable text on this screen to help instruct the user to push the +Register Guest button prior to pushing the Next button as a temporary solution. Our registrants are forgetting to push the +Register Guest button with the current configuration.

Thanks for your consideration of this enhancement!

![SummitEventsGuestRegButton](https://github.com/SFDO-Community/Summit-Events-App/assets/143199726/e75c961e-1853-43ae-9876-f3f7b0d7b081)

**Comment by tcdahlberg** [comment]
Hi @mcke0100,

I currently have in a branch a solution that might help with this, but I would love some feedback. What happens in my branch is that if information is filled in on the guest form and you hit the "Next" button a dialog modal pops up and asks if you want to continue. If you continue the form is blanked out and you progress to the next page. If you hit cancel it remains on the page with the information still in the form.

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/16785863/87dac9a7-ce39-4799-b4c9-847a03eae8cb)

I would love feedback. First if you think this is a good solutions and then on the default language in the dialog. I will be adding the ability to customize the dialog language, but getting a good default is always good for the bulk of users.

What do you think?

**Comment by mcke0100** [comment]
Thad.

I like this functionality a lot. I included Sue on this discussion as she may have an opinion. I think the message is good for a default. I really like the first sentence “You have unsaved guest information entered.” I am good with the second sentence but I am wondering if more information may help. “Do you wish to continue without Saving? Select Cancel to go back and add the current guest to your registration.”

Amy

**Comment by mcke0100** [comment]
My preference would be “You have unsaved Guest information entered.   Select Cancel to finish adding your guests”.

Then I would have the Cancel button blue, as that is what we’re suggesting to do.

Sue

**Comment by tcdahlberg** [comment]
Here you go:
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/16785863/3b164511-b5bf-4990-95be-cbe18829a7b9)
I also made it so you can customize the message in the modal as well as the button text via the event setup record. The default is what is appearing in the screenshot now.

**Comment by mcke0100** [comment]
This is great. Thanks Thad.

Amy

**Comment by rdblake21** [comment]
Tested in the Branch and works great!

**Comment by walt0019** [comment]
Sue Kolles and I confimred it looked good through Metecho.

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
