### ISSUE TITLE
The Event Instance End Time Text and Event Instance Start Time Text fields are displaying incorrectly for a 12 PM appointment.

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#516]
The Event Instance End Time Text and Event Instance Start Time Text fields on the Summit Event Registration records are displaying incorrectly for a 12 PM appointment.

**To Reproduce**
1. Go to an Instance.
2. Set Instance Start Time and Instance End Time to fall within the 12 PM hour.
3. Navigate to a Registration record.
4. Check on the Event Instance Start Time Text and Event Instance End Time Text fields and see 12 PM represented as 12 AM.

**Expected behavior**
It should display 12 PM as 12 PM and not switch to AM.

**Screenshots**
Please update the formulas to determine AM and PM if it is Greater Than or Equal to 12 it is set to 13 in the package.

IF( HOUR(summit__Event_Instance_Start_Time__c) >= 13, TEXT(HOUR(summit__Event_Instance_Start_Time__c) -12), TEXT(HOUR(summit__Event_Instance_Start_Time__c)))
&
":"
&
IF( MINUTE(summit__Event_Instance_Start_Time__c) < 10 , "0" & TEXT( MINUTE(summit__Event_Instance_Start_Time__c)), TEXT(MINUTE(summit__Event_Instance_Start_Time__c)))
&
" "
&
IF( HOUR(summit__Event_Instance_Start_Time__c) >= 12, "PM", "AM")

**Comment by walt0019** [comment]
Confirmed the formula fields were correct in the branch and sent a screenshot to Caitlyn to confirm as well.

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
