### ISSUE TITLE
[BUG] Confirmation Page - Total Row Shows Full Balance after Payment

### ISSUE THREAD

**Issue by mad2492** [SFDO-Community-Sprints/Summit-Events-App#517]
**Describe the bug**
On the SummitEventsConfirmation page (after making a payment), the table showing the event fees is presented to the user which appears to show the full Total Cost (which is confusing - it can be interpreted as the payment was not received)

**To Reproduce**
Successfully make a payment for a Summit Event Instance and you will be taken to a Confirmation Page that shows the same itemized list of fees with the same Total Balance, despite having just made a payment. 

**Expected behavior**
If we are presenting a table on the confirmation page, and we are claiming the Payment is Received, I expect the Total Row to show a $0.00 or the Total Row should say something else like "Payment Received" 

**Screenshots**
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/33240977-b148-410f-a412-a965ea993b7f)

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
