### ISSUE TITLE
[BUG] "This field is required" missing from required Additional Questions on Template

### ISSUE THREAD

**Issue by mad2492** [SFDO-Community-Sprints/Summit-Events-App#519]
**Describe the bug**
Inconsistent display of required help-text across fields in the event template. 

**To Reproduce**
Pick an Additional Question, and select "text area required" -- when you are viewing the rendered page, you'll see that the little help text does not appear like it does for the regular questions that are also required. 

**Expected behavior**
If field is marked required, I expect the help text to display under all required fields, not only the initial not-additional questions. 

**Screenshots**
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/cb42cb78-3c5c-4fa4-9cb9-292733201ebf)

It seems this additional div isn't included on the additional required questions:

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/7ff4e860-e461-4942-b7c6-58fceb7244d2)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox

**Comment by tcdahlberg** [comment]
On additional questions this is controlled by Error assist text:

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/16785863/da285ba6-c688-48ff-95fc-999afd2893af)

It could be argued that we have a default error assist which we could set up as an event record option.

That being said, if you tried error assist text and it didn't work let me know here.

Thanks!

**Comment by mad2492** [comment]
@tcdahlberg Yes, for the questions created w/ the Question object I do see the error text.

I am referring to the "Additional Questions 1-5" that appear on Page 1. 
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/23558618/5cd298af-00c5-4e73-9b32-ef50bacc031e)

**Comment by tcdahlberg** [comment]
@mad2492 , Got it. I clearly misunderstood. Thanks for the bug catch.

**Comment by tcdahlberg** [comment]
Included in beta release 0.31.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.31.0.1
