### ISSUE TITLE
Align Time Zone with the Date the Event is being held.

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#521]
While there is the ability to align Time Zone within a Summit Event, it doesn't accurately display the time zone when the event is happening if the time zone change/day light saving change is in the future.

For instance, St. Thomas is hosting a event in San Diego and selects Instance Tim Zone of Pacific Daylight Time (America/Los_Angeles) on the instance for an event on November 11th.  https://uofstthomasmn.my.salesforce-sites.com/summit__SummitEventsRegister?instanceID=a0zHq000009fOSU
On the Instance page, the time zone indicates that it is in PDT, when in fact it should be PST.  There is concern that it will not show up correctly within a calendar invite or someone see the date as incorrect or sloppy.  

On Registration Page, it displays, TOMMIE TAILGATE-SAN DIEGO
SATURDAY, NOVEMBER 11, 2023, 11:00 AM - 12:30 PM PDT.

In talking to Thad, after the Day Light Saving change, it will display TOMMIE TAILGATE-SAN DIEGO
SATURDAY, NOVEMBER 11, 2023, 11:00 AM - 12:30 PM PST, but not until that happens.

Please let me know if you have any questions.

**Comment by mad2492** [comment]
I second this! I had some users bickering about this same scenario with me earlier this week. We have some event in November and the page is showing EDT and the confirmation email of course says EDT even though it will be EST by the time the event occurs. Time is tricky to deal with. 

I was thinking of making the page just show ET, to alleviate the confusion. We haven't been around to see what happens when a time-change occurs w/ Summit Events, so I am glad to see the expected behavior is that it switches to EST on its own.

**Comment by walt0019** [comment]
Hi @mad2492 , I created this formula field on the Registration record based on Thad's help and where it will just display the word "Central," "Eastern," or "Pacific" based on the time zone at the end of a formatted Date, Time field.

summit__Event_Instance_Start_Date_Text__c + ", "+TEXT(YEAR(summit__Event_Instance_Start_Date__c))+", "+summit__Event_Instance_Start_Time_Text__c+" - "+summit__Event_Instance_End_Time_Text__c + " "+LEFT(summit__Event_Instance_Time_Zone__c, FIND(" ", summit__Event_Instance_Time_Zone__c) - 1)

We are thinking about adding it the the package, but feel free to use it now.

I'm also excited to see it update this weekend.

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/57462572/73e2ca95-bce5-4303-952a-14ef879f40db)

**Comment by walt0019** [comment]
Just to round out our conversation, the events display the Standard Time now.
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/57462572/e72d0f43-1b57-42ef-8824-3f000a2d1f0a)

**Comment by tcdahlberg** [comment]
Included in beta release 0.32.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.32.0.1
