### ISSUE TITLE
Increase field size on "Number of Guests" field on Summit Events Registration to 3 digits

### ISSUE THREAD

**Issue by jimhubert** [SFDO-Community-Sprints/Summit-Events-App#526]
On the 'Summit Events Registration' object the "Number of Guests' field is currently 2 digits long.  I am working with a school that is using Summit Events to register all seniors for a high school to visit which have more than the 99 possible guests the product currently allowed, so they are having an error message saying "number of guests outside of valid range for numeric field: 145" when they try to register 145 guests.

I believe the best solution is to update the field length field for the Number of Guests field from 2 to 3 digits, this will allow up to 999 guests to be added to a registration.

**Comment by jimhubert** [comment]
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/58151529/854f36aa-5668-47b2-a61a-10b3ef24c293)

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/58151529/c9bd3708-66f8-4add-9798-c4639f39e95b)

**Comment by jimhubert** [comment]
FYI @tcdahlberg   This is the issue we discussed today.

**Comment by tcdahlberg** [comment]
Included in beta release 0.32.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.32.0.1
