### ISSUE TITLE
[FEATURE] Honeypot and/or recaptcha on Registration page

### ISSUE THREAD

**Issue by mad2492** [SFDO-Community-Sprints/Summit-Events-App#527]
**Is your feature request related to a problem? Please describe.**
Our marketing team heavily promotes our events on various ad-platforms and it appears that exposes the Summit Events forms to bots. Our registrations are becoming plagued by fake registrations (particularly from GoogleAds, based on utm params) I don't expect the marketing team will stop their recruitment efforts, so I have to come up with a work-around. 

**Describe the solution you'd like**
Most public forms have some form of bot-mitigations. Most common is recaptcha, and maybe also a hidden honeypot field. 
I was not able to implement recaptcha as-is, because some actions have to be handled prior to clicking the Submit/Next button. (validate recaptcha as part of the Submit action)

I think it would be beneficial to anyone using this app to have some kind of captcha on the forms. We have to stand up against the bot-submissions. Or, at least maybe add a small section on the event page for Honeypot Config. Like,  this below could be some fields to populate in a new event:

_Section: Bot Mitigation_
[ ] Enable Honeypot field
[____] Enter Honeypot Label
Action when Honeypot field is filled: Picklist -> Cancel Registration, Delete Registration, Flag as "Possible Bot"

Then the page, when its rendered properly hides that field without my hacky-jquery solution. 

**Describe alternatives you've considered**
What I have done for the time being is I am using one of the "Additional Questions 1-5" as my honeypot field. And then on the Template page, I am doing some jquery logic to find the "honeypot label" div and hide it. When I get registrations that have a value in this specific field, and the field has that specific "honeypot label" i am Cancelling the registration immediately, via flow (and sending myself an email so I can gain insight as to the frequency of these submissions)

Of course, if our event needs to use all 1-5 Additional Questions, I have to probably use one of the other fields (like maybe Pronouns, and change its label to w/e my Honeypot label is)

Main issue is that my alternative solution is kind of impossible to explain to my users, so I have to make sure all events have this honeypot field somewhere. 

We are getting about 30 spam / bot submissions a day. 
 
**Are you willing and interested in being engaged during the development and testing process?**
yes - as much as I have the time/means to do so. 

@tcdahlberg  While you are exploring this, I was wondering if part of this solution could include capturing IPs during submission? The IPs are another way we can determine Bot submissions as well. Maybe it can be something that you have to Opt into, per Salesforce Org, like in the Summit Events Custom Settings there's a checkbox to control this. 

And then a new field on SEA Registrations to store IP.

**Comment by tcdahlberg** [comment]
Included in beta release 0.34.0.1

**Comment by mad2492** [comment]
[celebrate]     Marina Brillas reacted to your message:
________________________________

**Comment by tcdahlberg** [comment]
Included in production release 0.34.0.1
