### ISSUE TITLE
If use the / slash in a picklist item on a additional questions field, it does not render properly.

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#530]
**Describe the bug**
I used Additional Question 2, set it to a type of picklist.  In the picklist values, I added a combination value of Friend/Co-worker.  On the registration page drop-down, the slash "/" is not there.

**Expected behavior**
I would expect to see the /

**Screenshots**
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/4521914/7f39c4d5-86a5-4867-91b7-5fddc38d97cc)

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/4521914/6f39964f-0177-4c23-8bb1-653d2287babd)

**Desktop (please complete the following information):**
I am using the latest version of Chrome

**Comment by tcdahlberg** [comment]
For now note in documentation that these fields may not support custom characters.

**Comment by walt0019** [comment]
This issue is causing a conflict for St. Thomas in trying to map a Pronoun question with values like He/Him, She/Her and They/Them to the Pronouns question in Summit Events.

**Comment by walt0019** [comment]
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/57462572/e0994269-dbc2-48d1-bd7e-d38c62cd6b81)
