### ISSUE TITLE
Relabel or update the Preferred First Name Formatted field.

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#531]
User believe the Preferred First Name Formatted field should display the Preferred First Name field if provided or the First Name field.  Users are not expecting the Last Name of the registrant to also be included.

Suggestions to resolve the issue

* Relabel the field to be Preferred First Name Last Name Formatted.
* Or keep the field labeled as is, but update the formula to remove Last Name.
* Gauge interest if two formula fields (one first name field formatted should be provided as well as the first name formatted with last name should be provided within the package. 

Recently added Help Text, "This includes Preferred First Name if provided AND Last Name." so end users could understand.

**Comment by tcdahlberg** [comment]
Change the label of Preferred FIrst Name Formatted to "Preferred Full Name Formatted"

**Comment by tcdahlberg** [comment]
Included in beta release 0.32.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.32.0.1
