### ISSUE TITLE
[BUG] - Required Appointment Error

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#533]
**Describe the bug**
When creating an Appointment record when the "Required Appointment" is TRUE, there is a front-end validation error on the Appointment Page.  When you first get to the page, it essentially locks the ability to select an appointment, thus stopping registrations from moving forward.

**To Reproduce**
1. Create an Appointment record and market "Required Appointment" as TRUE
2. Register and get to the registration page

**Expected behavior**
Expectation is that when you land on the page, there is a red start to show it's required, and one is able to select it and progress forward. Should it not be selected, it highlights to show it's required when the registrant attempts to move forward. Other Appointments should be able to be selected regardless of the interaction with the required appointment.

**Screenshots**
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/9a6a26f5-135c-4711-ac6e-1d462afaebbd)

Nothing was selected or interacted with on the below image. It is how it appeared when I got to the page:
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/2c016d2a-2e57-452c-8c8a-ba05fc404061)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
This will need to be tested.  A short work around is to require the picklist or text on the Appointment Record.  While that won't fulfill the need to require a specific appointment, it will guide someone to what's needed.

**Comment by rdblake21** [comment]
@rdblake21 will review this again

**Comment by tcdahlberg** [comment]
Included in beta release 0.36.0.5

**Comment by tcdahlberg** [comment]
Included in production release 0.36.0.5
