### ISSUE TITLE
[BUG] - Blank Submit Page w/ only Custom Questions (no Guests)

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#540]
**Describe the bug**
When creating an event, there is an additional page that's blank, which creates an extra click and an awkward flow to the registration process.  I anticipate that when the admin uses a combination of standard and custom questions, only being asked to the registrant, that they go from the CustomQuestions page directly to the Confirmation Page as the submit page has nothing to review.

The submit page offers review of Guests, Appointment, Donations, Fees, so if those are not  in the event structure, the page should get skipped.

**To Reproduce**
1. Create an event using standard questions
2. Create a custom question record for the Registrant
3. Register for the event and see that you have 4 pages in the page flow (register, customquestions, submit, confirmation)

**Expected behavior**
If there are no guests, appointments, fees, or donations skip straight to the confirmation page. 

So Register-->Custom Question--->Confirmation

**Additional context**

**Comment by tcdahlberg** [comment]
Included in beta release 0.32.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.32.0.1
