### ISSUE TITLE
[BUG] - Mobile Calendar not Clickable

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#544]
**Describe the bug**
(https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007W6ymlSAB)
Error message is happening when attempting to click on any of the events to view its details. It is only happening for mobile screens, on desktop and phones.

The events are pulling correctly, but when we click on the event, nothing loads. The registration page should come up.

**To Reproduce**
1. Open the standard OOTB Calendar on a mobile device or reduce window
2. Try to click on an open event

**Expected behavior**
Regardless of the view, the event is clickable and someone can get to the registration page.

**Screenshots**
![image (4)](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/4c404181-7f4d-485c-ad03-b2bec41f37c2)

**Desktop (please complete the following information):**
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - Browser: Safari

**Comment by tcdahlberg** [comment]
Included in beta release 0.32.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.32.0.1
