### ISSUE TITLE
[BUG] - Cancellation Page isn't working as expected

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#545]
**Describe the bug**
Once a registration is received, the individual may be send the link to cancel their registration.  This is a Formula Hyperlink field that's capturing encrypted strings to hide the registration Id, but upon clicking, the registrant who is trying to cancel is getting an error page and nothing appears.

**To Reproduce**
1. Register for an event of any kind
2. go to the Registration record and click "Cancel Registration"
3. See error

**Expected behavior**
This was working before and expected to get to the cancellation page where the registrant has to click the additional button to cancel.

**Additional context**
Submitted from the Community - https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007Uv5is

**Comment by tcdahlberg** [comment]
Included in beta release 0.33.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.33.0.1
