### ISSUE TITLE
Microsoft Security Notice when trying to add calendar invite to outlook

### ISSUE THREAD

**Issue by mcke0100** [SFDO-Community-Sprints/Summit-Events-App#547]
**Describe the bug**
I just registered for the Finding Forward event and chose to add it to my Outlook calendar.     I got this security issue, see below.   I'm concerned there may be something going on with the Summit Events add to calendar feature that may be causing this.  I was able to save on my phone using the Add to Apple Calendar link.   There was no issue with that option.
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/143199726/fb794bd1-9039-4f1b-be94-151a3fa5d105)

**To Reproduce**
1. Register for an event (internal to UST - Finding Forward Event)
2. On the confirmation email, Click on the Add to Outlook Calendar link
3. Warning is displayed
4. Click Yes and continues on to process to add the event to my calendar

**Expected behavior**
No error/warning would be given and the event would be added to my calendar

**Screenshots**
attached above

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**

**Comment by tcdahlberg** [comment]
@mcke0100, Not sure what the resolution to this is. Microsoft introduced it last month:

https://support.microsoft.com/en-us/office/outlook-prompts-security-notice-opening-ics-files-after-installing-protections-for-microsoft-outlook-information-disclosure-vulnerability-released-dec-12-2023-df8647ef-1828-421b-a266-79120b6190bd

**Comment by mcke0100** [comment]
Thanks Thad.

From: Thaddaeus Dahlberg ***@***.***>
Sent: Wednesday, January 24, 2024 10:18 AM
To: SFDO-Community/Summit-Events-App ***@***.***>
Cc: McKenna, Amy M. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [SFDO-Community/Summit-Events-App] Microsoft Security Notice when trying to add calendar invite to outlook (Issue #547)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@mcke0100<https://github.com/mcke0100>, Not sure what the resolution to this is. Microsoft introduced it last month:

https://support.microsoft.com/en-us/office/outlook-prompts-security-notice-opening-ics-files-after-installing-protections-for-microsoft-outlook-information-disclosure-vulnerability-released-dec-12-2023-df8647ef-1828-421b-a266-79120b6190bd

-

**Comment by rdblake21** [comment]
Based on this, I'm going to close the issue with acknowledgement that this is a Microsoft update and not a current issue with Summit Events.
