### ISSUE TITLE
[BUG] Picklist Default Value for Custom Question

### ISSUE THREAD

**Issue by ramonjtorres** [SFDO-Community-Sprints/Summit-Events-App#548]
I have added a default value to my picklist custom question, but when accessing the register event form, that value does not appear, and if I continue without filling out that question and summit, this value does not appear in the Summit Events Registration record either.

**To Reproduce**
1. Create a custom questions for a picklist field, and add a Default Value:
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/22819607/704ab181-cc54-401e-ac5d-211084510c20)

2. Go to the Registration form, and look at the Custom Questions section, there is no value:
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/22819607/41f1e0ee-63dc-4741-9156-c5ceefa7fdda)

3. When you submit the registration form, there is no value on that field.

**Expected behavior**
The default value should be showed, and filled when you created the registration record.

**Comment by tcdahlberg** [comment]
Included in beta release 0.33.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.33.0.1
