### ISSUE TITLE
[BUG] - Additional information Header Appears when it shouldn't

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#553]
**Describe the bug**
The Additional Information Header is appearing, when nothing is underneath it. It should only appear when there is content that's relevant, but the logic seems to show the header when it appears elsewhere.

**To Reproduce**
1. Create an event and enable the Gender field on the Event record.
2. Register for the event
3. See that Additional Information header appears.

**Expected behavior**
It only appears when there is content below it.

**Screenshots**
Issue: ![image](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/751ddb41-1350-42e5-bb5b-54fb336feac1)

Registration Page Code logic:
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/704a8b7c-3607-43cc-8123-ef6959c2063b)

Apex Class logic:
The last three lines of this should be removed if they are going to appear above the header

https://github.com/SFDO-Community/Summit-Events-App/blob/master/force-app/main/default/classes/SummitEventsRegisterController.cls

![image](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/d61c40c2-c1bd-4e24-a711-3502a80d33ad)

**Comment by tcdahlberg** [comment]
Included in beta release 0.33.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.33.0.1
