### ISSUE TITLE
[BUG] - URL Filtering on Calendar with Audiences

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community-Sprints/Summit-Events-App#554]
**Describe the bug**
In reviewing the [.29 Release notes](https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/release-notes/0-29-0-1/#filtering-and-display-options-1), it speaks to being able to have a calendar pre-filtered if the URL parameters are met. In attempting to leverage this, we're finding that it's not working as expected.

When the URL parameter is updated, it remembers the cached calendar, so testing seems flawed in that the URL needs to be leveraged in an incognito window.  When testing difference links to put on different pages, it isn't consistent on what the URL parameter is actually doing and if it's truly working.

Example:
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/2b21bccd-53b2-4506-a5f9-8ef7f8b1eb46)
![image](https://github.com/SFDO-Community/Summit-Events-App/assets/60475518/eb6e5890-20c6-41e0-90cc-2dc918b91566)

Goal is to hide the dropdown and filter based on the URL parameters.

**To Reproduce**
1. Create an event with an audience selected
2. Create an instance
3. Go to the Calendar view
4. change the URL to see the dropdown disappear and then change the URL to various things to see if the instance shows or doesn't show.

**Expected behavior**
Expecting that the URL would present the same experience as the dropdown.

**Screenshots**
Listed above

**Additional context**
Would love to add more parameters on other multiselect picklists or fields, like "Type".

**Comment by tcdahlberg** [comment]
Included in beta release 0.33.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.33.0.1
