### ISSUE TITLE
Add an Accommodations field and a Dietary Restrictions field on the Summit Events Registration object 

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community-Sprints/Summit-Events-App#556]
**Is your feature request related to a problem? Please describe.**
Add an Accommodations field and a Dietary Restrictions field on the Summit Events Registration object to create consistent, standard fields to collect and report on these data points.

**Describe the solution you'd like**
I will likely create these fields within our instance to resolve this issue quickly, but wanted to document request for visibility and perhaps with feedback we might add fields to the package.

**Describe alternatives you've considered**
Users have used Additional Questions to capture this information in the past, but it is more difficult to report on consistently.  With the Summit Events Questions object, it is easy to create Questions to ask for the information, but users are left to create new fields that seem like they could be standard.

**Are you willing and interested in being engaged during the development and testing process?  Yes!  Again, we will probably create our own custom fields, but there might be traction to add the fields as standard, package delivered fields.

**Comment by rdblake21** [comment]
@walt0019 can you update this with the additional details you have on this issue.

**Comment by tcdahlberg** [comment]
Included in beta release 0.34.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.34.0.1
