### ISSUE TITLE
Should have ability to set default time zone for events

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#568]
**Describe the bug**
Right now, each time you create an event, if you are not in the central time-zone, you must change the time zone.  Should either default to the time-zone of the organization or user or have the ability to put in a custom setting of the desired default time zone.

**Screenshots**
<img width="274" alt="image" src="https://github.com/user-attachments/assets/c2af5b73-d48b-4f6e-8bab-14ea8ad0543b">

**Comment by walt0019** [comment]
Hi @dwhitig, good issue to bring up.  I was able to update the default value on the Instance Time Zone field.

<img width="780" alt="image" src="https://github.com/user-attachments/assets/bca13acc-6d2a-413a-bc83-16f4f76f7cfd">

**Comment by rdblake21** [comment]
Sounds like this is resolved
