### ISSUE TITLE
When an Event marked as cancelled, the closed event text should appear when someone goes to registration page

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community-Sprints/Summit-Events-App#576]
When an event is marked as Closed or Cancelled, the registration page for the event instances should show the "Event Closed Display Text".  Currently only if the event instance is marked as Closed or Cancelled does it display "Event Closed Display Text".  Some additional comments from Thad below....

Looks like the feed (or REST API) does hide events that are not active. So that is the only place those really do anything. Even there they only look for events that are also active (and ignore every other status)

**Comment by tcdahlberg** [comment]
Included in beta release 0.34.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.34.0.1
